### ISSUE TITLE
Fix Pow mantissa overflow

### ISSUE THREAD

**Issue by Razenpok** [Patashu/break_infinity.js#107]
There was a bug in `BreakInfinity.cs` which caused overflows in cases Pow(BigDouble with small mantissa, big power). Please check if break_infinity.js can get into a similar issue.

https://github.com/Razenpok/BreakInfinity.cs/issues/13
https://github.com/Razenpok/BreakInfinity.cs/commit/41b7463d6c1d52035914634a476a510987d17a5a

**Comment by Patashu** [comment]
new Decimal(1.15).pow(6000).toString()
'1.5383038312016823e+364'

agrees with the output of SpeedCrunch.

if that should have triggered the bug then no problem here.

re-open if I missed something
