### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by DatDerpyLuke** [Patashu/break_infinity.js#122]
Hi... How do I import the decimal class into the main javascript file?
I thought it was easier, I tried this:
![image](https://user-images.githubusercontent.com/80176779/129112470-d125330c-dc02-40b0-9ce9-3ce867a1470f.png)
Either import doesn't work or I messed up the variables (most likely)
![image](https://user-images.githubusercontent.com/80176779/129112553-4364aea7-704d-449b-9894-67821a5a7e83.png)
![image](https://user-images.githubusercontent.com/80176779/129112819-d77e8586-8cbc-4a93-825e-76ca143140c1.png)
Or I messed up the .add/.div/.etc
![image](https://user-images.githubusercontent.com/80176779/129112776-31e3fb99-0eb9-4101-81b1-65a477d29bf2.png)
![image](https://user-images.githubusercontent.com/80176779/129112804-5f908f67-1723-44b3-91b1-84aca9402b13.png)
Can you help me, please?

**Comment by Patashu** [comment]
so ironically I'm not actually a javascript expert so I don't know the correct way to do this lol

but both Synergism and Antimatter Dimensions just shove break_infinity.js into a script tag before anything that uses Decimal so they're both in the same scope, so maybe just do that?

https://github.com/Pseudonian/SynergismOfficial/blob/master/index.html

for a game that has working imports of the type you're trying to do, you can check out https://github.com/eevee/lexys-labyrinth/blob/master/js/game.js and try to figure out what it's doing differently from you. honestly, the syntax you're using looks the same so I have no immediate ideas.

sorry I'm not more help lol

**Comment by Razenpok** [comment]
You should use

```js
import Decimal from "break_infinity.js";
```

instead of

```js
import { Decimal } from "break_infinity.js";
```

**Comment by DatDerpyLuke** [comment]
> You should use
> 
> ```js
> import Decimal from "break_infinity.js";
> ```
> 
> instead of
> 
> ```js
> import { Decimal } from "break_infinity.js";
> ```

Hmm... I'll try it, if it works, I'll close the thread. Anyways, ty!

**Comment by DatDerpyLuke** [comment]
I changed the code, <script> tag had to be in head, and that import had to be removed. Sorry for bothering.

Patashu and Razenpok are literally the best devs I ever talked to.
