### ISSUE TITLE
'extend break_break_infinity.js to 1(1e1000) and beyond' checklist

### ISSUE THREAD

**Issue by Patashu** [Patashu/break_infinity.js#14]
First problem: After 1e(1e308), exponent can no longer be safely cast to a number. This means that log and anything relying on it (ln, log2, log10, pow) needs to be changed.

Second problem: After exp(1e308), exp needs to be able to handle larger input than Number (such as Decimal), and lines like 'x = new ExpHelper(this.toNumber());' and 'x = x.sub(tmp).toNumber();' need to be looked at.

Third problem: We'll probably want pow to start being able to accept larger than number (such as Decimal) around this point.

I don't think anything else would need to be changed. Notably all of these changes cause performance loss, maybe to the point where a break_break_break_infinity.js would be warranted.

**Comment by Patashu** [comment]
Also just for reference, here's SpectralFlame's HugeNumber that he claims can reach 10 ↑↑ 100000000.

https://github.com/cyip92/HugeNumber/blob/master/HugeNumber.java

**Comment by Patashu** [comment]
It looks like some to all of this can be solved by slabdrill-inspired changes, including making pow use pow10 and log10, a log10 version that just returns the exponent (rounding slightly depending on the mantissa value), and a log10 version that returns the nearest Decimal to what the previous log10 function would return.

It might not even hurt performance much...

**Comment by Patashu** [comment]
https://mrob.com/pub/comp/hypercalc/hypercalc-javascript.html

Another huge numbers calc.

**Comment by Razenpok** [comment]
I guess this issue became obsolete as of #39

**Comment by Patashu** [comment]
I'll make a new issue with what I actually want.
