### ISSUE TITLE
Consistency with break eternity.js

### ISSUE THREAD

**Issue by jakub791** [Patashu/break_infinity.js#141]
- break eternity has Decimal constants that get used in the internal code.
- break eternity has methods like Lamberta, gamma, lngamma.
- break eternity typescript's version consists of only 2 files 
- break Infinity code has functions like padEnd which were removed from break eternity a while ago 

Why it's all done this way? Can't this library and break eternity be somewhat consistent in terms of code and stuff? If you add something new to one library then also update the other one after it etc. Currently it feels like 2 completely unrelated libraries made by 2 different people (which is not true).

**Comment by Patashu** [comment]
It's kind of true actually lol. I didn't go back to update break_infinity much after poking at break_eternity, and Razenpok did a lot of the changes to b_i since.
