### ISSUE TITLE
add toPrecision()

### ISSUE THREAD

**Issue by erosson** [Patashu/break_infinity.js#16]
swarmsim and swarm-numberformat need it, and it exists for native numbers, decimal.js, and decimal.js-light.

This is enough for my unit tests to pass, but I'm not sure that it's correct everywhere, so no pull request:

		toPrecision(sigfigs) {
			return this.toFixed(sigfigs-1)
		}

**Comment by Patashu** [comment]
Looks like toPrecision() is like toFixed() while sigFigs is greater than the exponent, and like toExponent() otherwise?

`new Decimal(1e11).toPrecision(11)
"1.0000000000e+11"
new Decimal(1e10).toPrecision(11)
"10000000000"`

Lemme try that...

**Comment by Patashu** [comment]
Added, should work the same as decimal.js

**Comment by Patashu** [comment]
Found a weirdness with toPrecision() on very small numbers.

decimal.js:

```
new Decimal(1e-999).toPrecision(1)
"0"
new Decimal(1e-999).toPrecision(2)
"0.0"
new Decimal(1e-999).toPrecision(3)
"0.00"
new Decimal(1e-300).toPrecision(1)
"1e-300"
new Decimal(1e-300).toPrecision(2)
"1.0e-300"
new Decimal(1e-300).toPrecision(3)
"1.00e-300"
```

break_infinity.js:

(for all six)

```
break_infinity.html:312 Uncaught RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at Decimal.toFixed (break_infinity.html:312)
    at Decimal.toPrecision (break_infinity.html:319)
    at <anonymous>:1:23
```

Not sure how I want to fix it atm, since it's weird and inconsistent in decimal.js as well. But probably throwing an error is not ideal.

**Comment by erosson** [comment]
My tests pass with this, thanks!

No idea about the small number behavior - swarmsim never gets that small, and swarm-numberformat's not really tested for it either. Unsure if you're done with that part, so I'll let you close this.

**Comment by Patashu** [comment]
I think it's just a weird thing in decimal.js and the behaviour in break_infinity.js is fine so I'll close
