### ISSUE TITLE
toExponential() doesn't match decimal.js

### ISSUE THREAD

**Issue by erosson** [Patashu/break_infinity.js#17]
> var Decimal = require('decimal.js')
    undefined
    > var BDecimal = require('break_infinity.js/break_infinity.js')
    undefined
    > new Decimal('1e9999').toExponential(5)
    '1.00000e+9999'
    > new BDecimal('1e9999').toExponential(5)
    '1.000000e+9999'

swarmsim and swarm-numberformat depend on these for number formatting; expected them to match.

**Comment by Patashu** [comment]
`var numDigits = Math.max(1, Math.ceil(Math.log10(Math.abs(this.mantissa))));`

Is the fix, when it was 0 it was printing an extra decimal place for mantissas of 1

Also working on toPrecision(), I'll update when I have both ready

**Comment by Patashu** [comment]
Fixes should be done. I also added some fixes for 0 not printing the same way as in decimal.js

**Comment by erosson** [comment]
Tests pass with this, thanks!
