### ISSUE TITLE
Add getting started documentation

### ISSUE THREAD

**Issue by LouisITB** [Patashu/break_infinity.js#20]
It is unclear how to begin using this library if you are unfamiliar with decimal.js, would be nice to get some documentation on installing and adding to a new project, as well as converting an old project

**Comment by Patashu** [comment]
It's basically just the same as decimal.js. And if you already have decimal.js installed, you can just swap it to point to (or be if you directly include it) break_infinity.js and it'll work the same way.

https://github.com/MikeMcl/decimal.js/#load

Available as an NPM package here: https://www.npmjs.com/package/break_infinity.js

Is that all I need to write about? I can throw something quick in the readme.

**Comment by LouisITB** [comment]
I would suggest then to copy the Load and Use header from decimal.js readme.md to your own readme.md

**Comment by Patashu** [comment]
Like this?

**Comment by LouisITB** [comment]
Syntax highlighting would help but yes that is good thanks
https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

**Comment by Patashu** [comment]
Ah, that's how you do it!
