### ISSUE TITLE
break_break_infinity.js is not accurate in quadrillion digits

### ISSUE THREAD

**Issue by aarextiaokhiao** [Patashu/break_infinity.js#21]
In break_infinity.js
`> new Decimal('10').pow('1000000000000000').toString()`
`"1e+1000000000000000"`

In break_break_infinity.js:
`> new Decimal('10').pow('1000000000000000').toString()`
`"1.3716055782244467e+1000000000000000"`

Using pow() resulting as a number with quadrillion digits, break_break_infinity.js will have 30%-120% margin of error which is no good.

**Comment by Patashu** [comment]
Thanks, I will take a look at this soon.

**Comment by Patashu** [comment]
I have updated break_break_infinity.js to improve performance of exp and pow.

Let me know if you find any other cases where accuracy is critically bad.

**Comment by aarextiaokhiao** [comment]
I tested it and now it's accurate. Thanks.
