### ISSUE TITLE
pow inaccuracy at very high exponents

### ISSUE THREAD

**Issue by Patashu** [Patashu/break_infinity.js#26]
In break_infinity.js and break_break_infinity.js, we calculate pow generically as

```
return Decimal.pow10(value*this.log10());
```

This has a precision problem for very large numbers getting pow'd.

For break_break_infinity.js, here's the progression:

```
new Decimal("2e100000").pow(1.01).toString()
"2.0139111001331536e+101000"
new Decimal("2e1000000").pow(1.01).toString()
"2.0139111002681136e+1010000"
new Decimal("2e10000000").pow(1.01).toString()
"2.0139111018876377e+10100000"
new Decimal("2e100000000").pow(1.01).toString()
"2.013911110525099e+101000000"
new Decimal("2e100000000").pow(1.01).toString()
"2.013911110525099e+101000000"
new Decimal("2e1000000000").pow(1.01).toString()
"2.0139111796247904e+1010000000"
new Decimal("2e10000000000").pow(1.01).toString()
"2.013905098861038e+10100000000"
new Decimal("2e100000000000").pow(1.01).toString()
"2.013869720236098e+101000000000"
new Decimal("2e1000000000000").pow(1.01).toString()
"2.0140820013086556e+1010000000000"
new Decimal("2e10000000000000").pow(1.01).toString()
"2.0169145547303304e+10100000000000"
new Decimal("2e100000000000000").pow(1.01).toString()
"1.9809567785503388e+101000000000000"
new Decimal("2e1000000000000000").pow(1.01).toString()
"1.7782794100389228e+1010000000000000"
new Decimal("2e10000000000000000").pow(1.01).toString()
"1e+10100000000000000"
```

The problem is due to the use of log10. all of the precision slowly vanishes until nothing is left:

```
10000000000000000+0.30102999566398119521
10000000000000000
```

obviously, making a log10_decimal or log10_biginteger would not fix this problem.

The line will have to be something different that allows the precision to continue to exist. It's clear that the 'high part' and the 'low part' of log10 mean something different - one mostly influences the exponent, one mostly influences the mantissa. Maybe this will lead to a solution (and possibly even a speedup)?

**Comment by Patashu** [comment]
We can turn it into

```
return Decimal.pow10(value*this.exponent + value*Math.log10(this.mantissa));
```

which has a precision loss, but we can split it up into fractional and integer component and just shove the integer into the exponent and the fractional part into the mantissa:

```
var temp = value*this.exponent;
var newexponent = Math.trunc(temp);
var residue = temp-newexponent;
var newmantissa = Math.pow(10, value*Math.log10(this.mantissa)+residue);
return Decimal.fromMantissaExponent_noNormalize(newmantissa, newexponent);
```

But it has a precision loss, as demonstrated:

speedcrunch:

```
2e1000000^pi
=3.97469140906667370141e3141593
```

```
new Decimal("2e1000000").pow(Math.PI).toString()
"3.974691407024013e+3141593"
new Decimal("2e1000000").oldpow(Math.PI).toString()
"3.9746914076926876e+3141593"
```

The precision loss is in getting the residue:

```
newexponent:3141592
residue:0.6535897930152714
temp:3141592.653589793
```

if we have the rest of residue:

```
10^(pi*log(2)/log(10)+0.65358979323846264338)
= 39.74691409066673701385
```

So the bigger our exponent is, the less of residue we learn. So this doesn't scale to b_b_i levels yet.

**Comment by Patashu** [comment]
The solution seems to work fine over b_i ranges, for b_b_i we can just slap ExpHelper on it.

**Comment by 1234abcdcba4321** [comment]
BigInteger * Number = BigInteger.times(Decimal.toBigInteger(Number*1e17)).div(1e17)

**Comment by Patashu** [comment]
That's one way to do it. You can also do it by slapping it into an abitrary precision ExpHelper (my name for decimal.js in this library) and then trunc, toFixed() to turn it back into a big-integer. Not sure which way is faster.

Probably a quick 'cut off the last 17 digits' thing is literally a string operation, rofl.
