### ISSUE TITLE
Optimizing powers of 10

### ISSUE THREAD

**Issue by KidaCodes** [Patashu/break_infinity.js#28]
Great library, I've been working with it as a bases for a ES6 module based number lib. (Trying to compress distribution size.)

You can consider shrinking the source code by modifying the powerof10 = [....] array to be auto generated.

Example:
```javascript
const NUMBER_EXP_MAX = Number(Number.MAX_VALUE.toString().split("e")[1]) - 1;
const NUMBER_EXP_MIN = Number(Number.MIN_VALUE.toString().split("e")[1]) + 1;
let powersof10 = [];
for (let i = NUMBER_EXP_MIN; i <= NUMBER_EXP_MAX; i++) {
    powersof10.push(Number('1e' + i));
}
const indexof0inpowersof10 = -NUMBER_EXP_MIN;
```

This would negate the need to keep that vary long array in the source. Number("string") also does not suffer from the floating point errors that Math.pow(10,e) does.

**Comment by Patashu** [comment]
Cool idea. I measured it to take about 0.1ms, so it's not a performance loss.

**Comment by KidaCodes** [comment]
It is also only ran once on script initialization (startup); so it will have zero performance impact to the actual Decimal class.

**Comment by Patashu** [comment]
Ok, implemented. Thanks!
