### ISSUE TITLE
type definitions for typescript

### ISSUE THREAD

**Issue by KeTr** [Patashu/break_infinity.js#29]
I'd like to incorporate this into an Angular project, but there seems to be no type definitions for Typescript. I tried some workarounds to get it to work, but couldn't. Would you be willing to add type declarations for usage with Typescript?

**Comment by Patashu** [comment]
I have never used Angular or Typescript before, so I'd need a tutorial.

**Comment by Patashu** [comment]
It looks like it's to do with having a separate type declarations file:

https://github.com/MikeMcl/decimal.js/blob/master/decimal.d.ts

**Comment by scorzy** [comment]
To use with Angular 6 you can:
- add "./node_modules/break_infinity.js/break_infinity.js" to scripts in angular.json
- write yours type definition in typings.d.ts (you can copy some definition from the file i pushed, note that is not commented and not completed)

I don't know how to add the type definitions to the npm package but it should be great.

**Comment by Patashu** [comment]
Once again, decimal.js teaches us the way:

https://github.com/MikeMcl/decimal.js/blob/master/package.json

Notice the line  "types": "decimal.d.ts" ? That has to be copied.

**Comment by Patashu** [comment]
Should be fixed by https://github.com/Patashu/break_infinity.js/pull/32 , let me know if there are any further problems!
