### ISSUE TITLE
Use a module bundler to split the project into modules

### ISSUE THREAD

**Issue by bary12** [Patashu/break_infinity.js#31]
Modern Javascript development is usually done using a module bundler, which has some very clear advantages.

* Allows splitting the project into modules (files) instead of having it in a single file, which makes the code more maintainable and readable. This will welcome more people (including me) to contribute to the project.
* Easy integration with Babel to allow writing ES6 code while still maintaining cross-browser support. (See #1)
* Tree shaking and code uglifying as a normal part of the build process

[Rollup](https://www.npmjs.com/package/rollup) is considered the best for libraries as it produces the lightest bundle.

**Comment by Patashu** [comment]
Do you have a good example of a JS project on github that uses Rollup?

**Comment by bary12** [comment]
Some of the big ones (vuejs/vue, facebook/react) use it. [here](https://github.com/rollup/rollup-starter-project) is an example starter project

**Comment by Razenpok** [comment]
Build pipeline based on https://github.com/egoist/bili was introduced in #39, we can close this issue

**Comment by Patashu** [comment]
Sure.
