### ISSUE TITLE
official C# translation

### ISSUE THREAD

**Issue by Patashu** [Patashu/break_infinity.js#34]
While it's technically out of the scope of the repository (making a second one would be ok), a lot of people want to make incremental games that go above 1e308 in C#/Unity, and a mechanical translation of break_infinity.js into C# would be satisfactory for those purposes.

If anyone out there does this, let me know and I can link it from this repository and give it my official blessing.

**Comment by elementh** [comment]
That would be really interesting

**Comment by Patashu** [comment]
closed by https://github.com/Patashu/break_infinity.js/commit/b68743b4c3c2119a2a57f9f5b00b2ee1dc93e4de
