### ISSUE TITLE
TypeScript migration

### ISSUE THREAD

**Issue by Razenpok** [Patashu/break_infinity.js#38]
As per AD Discord, we are approaching a point where we would benefit from BI optimizations. I'll try to squeeze some more performance from low-level optimizations, like less allocations and type consistency, and I think working on it would be more safe/efficient with TypeScript
Plus, we will always have fresh TS definitions out of the box!

**Comment by Patashu** [comment]
Good luck! Probably also investigate the idea of ditching mantissa and just storing the Decimal as its log10 representation, which could be faster.
