### ISSUE TITLE
Add safelog10

### ISSUE THREAD

**Issue by Patashu** [Patashu/break_infinity.js#45]
Same as add(1).log10()

**Comment by Razenpok** [comment]
Maybe `clampMin(1).log10()` instead of `add(1).log10()`?

**Comment by Patashu** [comment]
If the add 1 isn't mathematically important then sure, I wasn't sure from Garnet's description

**Comment by Razenpok** [comment]
I think the point of this operation is to clamp the result in the range [0, +Infinity)

**Comment by Razenpok** [comment]
Hence +1 and clampMin(1) would result in different results

**Comment by Razenpok** [comment]
But apart from `clampMin(1).log(10)` there's also `clampMin(1).log(10)`. How should we call each of them? Which one is "safelog"?

**Comment by Razenpok** [comment]
idk, this idea doesn't LGTM anymore

**Comment by Patashu** [comment]
`log10(0)` is `NaN`; why would you ever want to write `clampMin(0).log10()` ? the only other non-arbitrary remaining value is `1`, making the definition unambiguous

**Comment by Razenpok** [comment]
Oh, right
I've been testing Math.log10(0) instead, which returns -Infinity. Another compatibility bug?

**Comment by Patashu** [comment]
What compatibility bug?

```
Math.log10(0)
-Infinity
Decimal.log10(0)
-Infinity
```

**Comment by Razenpok** [comment]
WDYM by that then

>log10(0) is NaN; why would you ever want to write clampMin(0).log10() ?

**Comment by Patashu** [comment]
Sorry by NaN I meant non-finite (I tested in speedcrunch where it says 'undefined for argument domain', I didn't bother to check what it does in Javascript).

Let me put it this way:

If you have new Decimal(-1).clampMin(0).log10() it returns a non-finite number (-Infinity). But if you have new Decimal(-1).clampMin(1).log10() it returns a finite number (0). A safelog that isn't actually safe (returns a non-finite number for most of its arguments) is obviously not intended. So, we unambiguously define safelog10() as clampMin(1).log10().

**Comment by Razenpok** [comment]
But then it  will effectively cut the result range in half - we won't ever get negative number result from it (e.g. like log10(0.01))

**Comment by Patashu** [comment]
I think the assumption is that we don't want results lower than 0?

**Comment by Razenpok** [comment]
`pLog10()`? :thonk:
