### ISSUE TITLE
Add Node.js support

### ISSUE THREAD

**Issue by Patashu** [Patashu/break_infinity.js#5]
No clue how you do this.

**Comment by erosson** [comment]
Tried this in node with swarm-numberformat, and it seems to run fine. (Some decimal.js incompatibilities, not node-specific I think, will isolate and file bugs later.)

Packaging for npm would be nice so I can add it to my project like other dependencies, but you - the author - would have to re-publish it periodically: https://docs.npmjs.com/getting-started/publishing-npm-packages

If you just want to push to git and not think about node, I was able to add it to my project as-is this way:

    $ yarn add Patashu/break_infinity.js#master
    
    var Decimal = require('break_infinity/break_infinity.js')

I think `npm install --save Patashu/break_infinity.js#master` would also work, but I didn't test it

**Comment by Patashu** [comment]
Thanks, I'll look into npm on the weekend.

**Comment by Patashu** [comment]
Ok, I think I did it correctly?

https://www.npmjs.com/package/break_infinity.js

**Comment by erosson** [comment]
Looks right to me!

With node packages, you're responsible for publishing a new version number when you make changes - `npm version <patch|minor|major> && npm publish`  - or people using your library won't see it. Doesn't look like #16 and #17 are in v1.0.0.

If you don't want to deal with version numbers, you can tell people to reference a git commit instead - [that's what I'm doing here, to use it until there's a version number](https://github.com/erosson/swarm-numberformat/blob/5e9096baf8db6a233b37241b8dadf21e987d1ed0/package.json#L44). Publishing new version numbers is The Right Way though.

Also, you should probably `git config --global push.followTags true`. Creating a version number creates a git tag, which should probably be pushed to github, but for some reason `git push` doesn't push tags unless you set that config. Tags should appear here: https://github.com/Patashu/break_infinity.js/tags

**Comment by Patashu** [comment]
Yeah, I'll publish again when I get home. I was waiting until you confirmed all the new changes are fine, since I didn't want to publish it in a potentially broken state. Thx for the tips.

**Comment by Patashu** [comment]
Republished
