### ISSUE TITLE
Specify an ignore file for package's published artifacts

### ISSUE THREAD

**Issue by EdricChan03** [Patashu/break_infinity.js#79]
If one looks at [`break_infinity.js@1.2.0`](https://unpkg.com/browse/break_infinity.js@1.2.0/)'s files on [Unpkg](https://unpkg.com), you can see that there are files that are redundant were included as part of the package:

![Screenshot of a list of files from the `break_infinity.js@1.2.0` package on Unpkg](https://user-images.githubusercontent.com/20047125/88032044-00e4ed00-cb70-11ea-946f-6c0923a29ae6.png)

For e.g.:
- `bili.config.ts`
- `tsconfig.json`
- `tslint.json`
- `typedoc.ts`
- `types` directory
- `.github` directory

Specifying a [`.npmignore`](http://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html) file or simply specifying the directory to be used to publish the artifacts from would fix this issue.

(P.S. Interestingly enough the npm documentation also has additional information on what should be published in a package in the [developer guide](https://docs.npmjs.com/misc/developers), specifically the [Keeping files out of your package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) section:

> Use a `.npmignore` file to keep stuff out of your package. If there’s no `.npmignore` file, but there is a `.gitignore` file, then npm will ignore the stuff matched by the `.gitignore` file. If you want to include something that is excluded by your `.gitignore` file, you can create an empty `.npmignore` file to override it. Like git, npm looks for `.npmignore` and `.gitignore` files in all subdirectories of your package, not only the root directory.

)

Alternatively, we might have to restructure the whole project.. See this [StackOverflow answer](https://stackoverflow.com/a/44617078) to writing NPM modules in TypeScript.

**Comment by Razenpok** [comment]
Fixed in 1197384
