### ISSUE TITLE
Self-division Does not result in 1

### ISSUE THREAD

**Issue by briangithex** [Patashu/break_infinity.js#97]
Repro:
```
var x = new Decimal('4e100000000000000000000');
x.dividedBy(x); //10
```

Expected:
```
var x = new Decimal('4e100000000000000000000');
x.dividedBy(x); //1
```

**Comment by Anthios314** [comment]
Unless I missed something, 4e100000000000000000000 > 1e(9e15), the limit of this number engine. So I wouldn't expect a correct result at such massive values, even with this program.

**Comment by 1e1000000** [comment]
Somehow Synergism 1000% bug probably because this

**Comment by briangithex** [comment]
> Somehow Synergism 1000% bug probably because this

You're correct.  I discovered this bug by trying to figure out why Synergism was displaying 1000% instead of 100%.

**Comment by Razenpok** [comment]
Could you please provide a real use-case repro of this bug? I'm not sure the code from the first post is valid, as @Anthios314 pointed out.

**Comment by briangithex** [comment]
Razenpok is correct.  Apparently, Synergism was/is inadvertently using larger numbers than break_infinity supports.
